services:
  app:
    container_name: pwntools
    build:
      context: ..
      dockerfile: docker/Dockerfile.tools    
    volumes:
      - ../src:/app/src                    
      - ../package.json:/app/package.json
      - ../package-lock.json:/app/package-lock.json
      - C:/Users/Lenovo/Desktop/coding/next tuts/no-pwn-intended/docker/scripts:/docker/scripts
    ports:
      - "3000:3000"
    command: npm run dev                    
